packages:
  - apps/*
  - packages/*

catalog:
  '@nestjs/common': 10.2.10
  '@nestjs/config': 3.1.1
  '@nestjs/core': 10.2.10
  '@nestjs/jwt': 11.0.0
  '@nestjs/passport': 10.0.3
  '@nestjs/platform-express': 10.2.10
  '@prisma/client': 5.7.0
  '@tanstack/react-query': 5.25.0
  '@testing-library/jest-dom': 6.1.5
  '@testing-library/react': 14.1.2
  '@typescript-eslint/eslint-plugin': 6.13.2
  '@typescript-eslint/parser': 6.13.2
  autoprefixer: 10.4.16
  axios: 1.6.2
  date-fns: 2.30.0
  eslint: 8.55.0
  jest: 29.7.0
  lodash-es: 4.17.21
  next: 14.0.4
  passport: 0.7.0
  passport-jwt: 4.0.1
  postcss: 8.4.31
  prettier: 3.1.0
  prisma: 5.7.0
  react: 18.2.0
  react-dom: 18.2.0
  react-hook-form: 7.48.0
  tailwindcss: 3.3.6
  turbo: 1.10.16
  typescript: 5.3.3
  zod: 3.22.4
  zustand: 4.4.1

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - prisma
